import type { CertificateSigner, Company, Shareholder } from "../../../types/models";

export type Capital = { title: string; totalShares: number; nominalValue: number; rows: Array<{ index:number; shareholder:Shareholder; shares:number; nominal:number; value:number }> };
export type CompositionDocument = { company: Company; signer: CertificateSigner; logo: string; signature: string; subscribed: Capital; paid: Capital; dateText: string; fileName: string; professionalNumber: string };
const money = new Intl.NumberFormat("es-CO", { style:"currency", currency:"COP", maximumFractionDigits:0 });
export const formatMoney=(n:number)=>money.format(n).replace("COP", "$");
export const formatNumber=(n:number)=>new Intl.NumberFormat("es-CO",{maximumFractionDigits:0}).format(n);
export function distribute(total:number, shareholders:Shareholder[]) { const raw=shareholders.map((s,i)=>({i, raw:total*s.percentage/100})); const base=raw.map(x=>Math.floor(x.raw)); let rest=total-base.reduce((a,b)=>a+b,0); raw.sort((a,b)=>(b.raw-Math.floor(b.raw))-(a.raw-Math.floor(a.raw))||a.i-b.i); for(let i=0;i<rest;i++)base[raw[i%raw.length].i]++; return base; }
function capital(title:string,totalShares:number,nominalValue:number, shareholders:Shareholder[]):Capital { const shares=distribute(totalShares,shareholders); return {title,totalShares,nominalValue,rows:shareholders.map((s,i)=>({index:i+1,shareholder:s,shares:shares[i],nominal:nominalValue,value:shares[i]*nominalValue}))}; }
const units=["cero","uno","dos","tres","cuatro","cinco","seis","siete","ocho","nueve","diez","once","doce","trece","catorce","quince","dieciséis","diecisiete","dieciocho","diecinueve","veinte","veintiuno","veintidós","veintitrés","veinticuatro","veinticinco","veintiséis","veintisiete","veintiocho","veintinueve"];
function words(n:number):string { if(n<30)return units[n]; if(n<100){const d=["","","treinta","cuarenta","cincuenta","sesenta","setenta","ochenta","noventa"][Math.floor(n/10)];return n%10?`${d} y ${words(n%10)}`:d;} if(n<1000){const h=Math.floor(n/100);return `${h===1?"ciento":["","ciento","doscientos","trescientos","cuatrocientos","quinientos","seiscientos","setecientos","ochocientos","novecientos"][h]}${n%100?` ${words(n%100)}`:""}`;} if(n<1000000){const k=Math.floor(n/1000);return `${k===1?"mil":`${words(k)} mil`}${n%1000?` ${words(n%1000)}`:""}`;} return String(n); }
export const SIGNATURE_MISSING = "La imagen de firma de este firmante no está disponible. Edita el firmante y vuelve a cargar su firma.";
/** `signatureMissing`: el firmante tiene referencia pero el PNG no existe o no se puede leer. */
export function validate(company:Company|null,signer:CertificateSigner|null,logo:string|null,signature:string|null,signatureMissing=false):string[] {const e:string[]=[];if(!company)e.push("Selecciona una empresa.");else {if(!company.logoFile||!logo)e.push("La empresa debe tener un logo disponible.");if(!company.nit||!company.dv||!company.ciudad)e.push("La empresa debe tener NIT, DV y ciudad.");if(!company.subscribedTotalShares||!company.subscribedNominalValue||!company.paidTotalShares||!company.paidNominalValue||!company.shareholders.length)e.push("La empresa seleccionada no tiene configurada toda la información accionaria.");if(Math.abs(company.shareholders.reduce((a,s)=>a+s.percentage,0)-100)>0.000001)e.push(`La participación accionaria debe sumar 100%. Actualmente suma ${company.shareholders.reduce((a,s)=>a+s.percentage,0)}%.`);}if(!signer)e.push("Selecciona un firmante.");else if(signatureMissing||!signer.signatureAvailable)e.push(SIGNATURE_MISSING);else if(!signature)e.push("Cargando la firma del firmante…");return e;}
export function build(company:Company,signer:CertificateSigner,logo:string,signature:string,generatedAt=new Date()):CompositionDocument {const p=signer.professionalDocument.replace(/\D/g,"");const day=generatedAt.getDate(),year=generatedAt.getFullYear(),month=["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"][generatedAt.getMonth()];return {company,signer,logo,signature,subscribed:capital("CAPITAL SUSCRITO",company.subscribedTotalShares!,company.subscribedNominalValue!,company.shareholders),paid:capital("CAPITAL PAGADO",company.paidTotalShares!,company.paidNominalValue!,company.shareholders),professionalNumber:p,dateText:`Para constancia se firma en la ciudad de ${company.ciudad}, a los ${words(day)} (${day}) días del mes de ${month} del año ${words(year)} (${year})`,fileName:`Composicion_Accionaria_${company.razonSocial}_${generatedAt.toISOString().slice(0,10)}.pdf`};}
