import { useState } from "react";
import { ImagePlus, Pencil, Plus, Trash2 } from "lucide-react";
import { Alert, Button, Card, ConfirmDialog, EmptyState, Field, Input, Loader, Modal, PageHeader, useToast } from "../components/ui";
import { useAsync } from "../hooks/useAsync";
import { signerService } from "../services/signerService";
import type { CertificateSigner, CertificateSignerInput } from "../types/models";

const empty: CertificateSignerInput = { name: "", role: "", professionalDocument: "", signatureFile: "" };
export function SignersPage() {
  const toast = useToast(); const list = useAsync(() => signerService.list(), []);
  const [editing, setEditing] = useState<CertificateSigner | null | undefined>(); const [removing, setRemoving] = useState<CertificateSigner | null>(null);
  const [values, setValues] = useState<CertificateSignerInput>(empty); const [preview, setPreview] = useState<string | null>(null); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  function open(s: CertificateSigner | null) { setEditing(s); setValues(s ? { name:s.name,role:s.role,professionalDocument:s.professionalDocument,signatureFile:s.signatureFile } : empty); setPreview(null); setError(null); if(s) void signerService.dataUrl(s.signatureFile).then(setPreview); }
  async function pick() { try { const r=await signerService.pickSignature(); if(r){setValues(v=>({...v,signatureFile:r.signatureFile}));setPreview(r.dataUrl);} }catch(e){setError((e as Error).message)} }
  async function save(){ if(!values.name.trim()||!values.role.trim()||!values.professionalDocument.trim()||!values.signatureFile){setError("Completa todos los campos e importa la firma PNG.");return;}setBusy(true);try{editing?await signerService.update(editing.id,values):await signerService.create(values);toast(editing?"Firma actualizada.":"Firma creada.");setEditing(undefined);void list.reload();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function remove(){if(!removing)return;setBusy(true);try{await signerService.remove(removing.id);toast("Firma eliminada.");setRemoving(null);void list.reload()}catch(e){toast((e as Error).message,"error")}finally{setBusy(false)}}
  return <><PageHeader eyebrow="Datos" title="Firmas" description="Firmantes reutilizables para certificados." actions={<Button variant="primary" icon={<Plus size={15}/>} onClick={()=>open(null)}>Nueva firma</Button>}/><Card flush title="Firmas registradas">{list.loading&&!list.data?<Loader/>:(list.data?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Firmante</th><th>Cargo</th><th>Documento profesional</th><th/></tr></thead><tbody>{list.data.map(s=><tr key={s.id} className="is-clickable" onClick={()=>open(s)}><td className="table__primary">{s.name}</td><td>{s.role}</td><td>{s.professionalDocument}</td><td className="actions" onClick={e=>e.stopPropagation()}><Button variant="ghost" size="sm" iconOnly icon={<Pencil size={14}/>} aria-label="Editar" onClick={()=>open(s)}/><Button variant="ghost" size="sm" iconOnly icon={<Trash2 size={14}/>} aria-label="Eliminar" onClick={()=>setRemoving(s)}/></td></tr>)}</tbody></table></div>:<EmptyState title="Aún no hay firmas" description="Crea un firmante para usarlo en composición accionaria." action={<Button variant="primary" onClick={()=>open(null)}>Nueva firma</Button>}/>)}</Card><Modal open={editing!==undefined} title={editing?"Editar firma":"Nueva firma"} onClose={()=>setEditing(undefined)} locked={busy} footer={<><Button variant="ghost" onClick={()=>setEditing(undefined)}>Cancelar</Button><Button variant="primary" loading={busy} onClick={()=>void save()}>Guardar</Button></>}><div className="stack">{error&&<Alert tone="danger">{error}</Alert>}<Button icon={<ImagePlus size={14}/>} onClick={()=>void pick()}>{values.signatureFile?"Cambiar firma PNG":"Cargar firma PNG"}</Button>{preview&&<img src={preview} alt="Vista previa de firma" style={{maxHeight:80,maxWidth:260,objectFit:"contain"}}/>}<Field label="Nombre" required>{id=><Input id={id} value={values.name} onChange={e=>setValues(v=>({...v,name:e.target.value}))}/>}</Field><Field label="Cargo" required>{id=><Input id={id} value={values.role} onChange={e=>setValues(v=>({...v,role:e.target.value}))}/>}</Field><Field label="Documento profesional" required hint="Ej. TP-290048">{id=><Input id={id} value={values.professionalDocument} onChange={e=>setValues(v=>({...v,professionalDocument:e.target.value}))}/>}</Field></div></Modal><ConfirmDialog open={!!removing} danger title="Eliminar firma" message="La firma y su imagen se eliminarán." confirmLabel="Eliminar" loading={busy} onCancel={()=>setRemoving(null)} onConfirm={()=>void remove()}/></>;
}
